version: '3.8'

services:
  food-postgres-database:
    image: postgres:17
    container_name: food-postgres-database
    env_file:
      - "./food-backend/.env"
    ports:
      - "5432:5432"
    networks:
      - food-network

  food-mongo-database:
    image: mongo:latest
    container_name: food-mongo-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - food-network

  food-redis-database:
    image: redis:7-alpine
    container_name: redis_data
    command: --requirepass ${REDIS_PASSWORD:-pass}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - food-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka_server
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NUM_PARTITIONS: 1
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - food-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - food-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  kafka_data:

networks:
  food-network:
    driver: bridge