services:
  food-postgres-database:
    image: postgres:latest
    container_name: food-postgres-database
    environment:
      - POSTGRES_USER={POSTGRES_USER}           
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}    
      - POSTGRES_DB={POSTGRES_DB}         
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - ./food-backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistência dos dados
    networks:
        - food-network

  food-mongo-database:
    image: mongo:latest
    container_name: food-mongo-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}   
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"                      
    volumes:
      - mongo_data:/data/db 
    expose:
      - ${MONGO_PORT}
    env_file:
      - ./food-backend/.env
    networks:
      - food-network

  food-redis-database:
    image: redis:7-alpine
    container_name: redis_data
    env_file:
      - path: ./food-backend/.env
        required: true
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      --requirepass pass

    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis_data:/data
    networks:
      - food-network
    
volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  food-network:
    driver: bridge