services:
  food-postgres-database:
    image: postgres:17
    container_name: food-postgres-database
    env_file:
      - "./food-backend/.env"
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: pass
    #   POSTGRES_DB: db
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - food-network

  food-mongo-database:
    image: mongo:latest
    container_name: food-mongo-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"  # Usando valor padrão se não definido
    volumes:
      - mongo_data:/data/db
    networks:
      - food-network

  food-redis-database:
    image: redis:7-alpine
    container_name: redis_data
    command: --requirepass ${REDIS_PASSWORD:-pass}  # Usando valor padrão se não definido
    ports:
      - "6379:6379"  # Usando valor padrão se não definido
    volumes:
      - redis_data:/data
    networks:
      - food-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  food-network:
    driver: bridge